# Generated by Django 4.2.3 on 2023-11-14 02:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='Likes',
        ),
        migrations.RenameModel(
            old_name='Match',
            new_name='Matches',
        ),
    ]
