# Generated by Django 4.2.3 on 2023-11-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_like_likes_rename_match_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
